/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePickerComponent: typeof import('./components/forms/DatePickerComponent.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputNumberComponent: typeof import('./components/forms/InputNumberComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InputTextComponent: typeof import('./components/forms/InputTextComponent.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordComponent: typeof import('./components/forms/PasswordComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectComponent: typeof import('./components/forms/SelectComponent.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    TextareaComponent: typeof import('./components/forms/TextareaComponent.vue')['default']
  }
}
